import tkinter

screen  = tkinter.Tk()
screen.geometry("500x500")
screen.title(  "ADDRESS BOOK")

lb = tkinter.Listbox(screen)
e1 = tkinter.Entry(screen)
e2 = tkinter.Entry(screen)
e3 = tkinter.Entry(screen)
e4 = tkinter.Entry(screen)
e5 = tkinter.Entry(screen)
l1= tkinter.Label(screen,text="my address book")
l2= tkinter.Label(screen,text="name")
l3= tkinter.Label(screen,text = "address")
l4= tkinter.Label(screen,text = "mobile")
l5= tkinter.Label(screen,text="email")
l6= tkinter.Label(screen,text= "birthday")
b1 = tkinter.Button(screen,text="open")
b2 = tkinter.Button(screen,text = "save")
b3 = tkinter.Button(screen,text = "load")
b4 = tkinter.Button(screen,text = "edit")
b5 = tkinter.Button(screen,text= "delete")

lb.grid(row=2,column=1)
e1.grid(row=2,column=4)
e2.grid(row=3,column=4)
e3.grid(row=4,column=4)
e4.grid(row=1,column=4)
e5.grid(row=1,column=4)
l1.grid(row=1,column=1)
l2.grid(row=2,column=3)
l3.grid(row=3,column=3)
l4.grid(row=4,column=3)
l5.grid(row=1,column=3)
l6.grid(row=1,column=3)
b1.grid(row=1,column=3)
b2.grid(row=1,column=1)
b3.grid(row=1,column=1)
b4.grid(row=1,column=1)
b5.grid(row=1,column=1)

screen.mainloop()